name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git openjdk-17-jdk unzip libltdl-dev
        pip install --upgrade pip
        pip install cython==0.29.33 buildozer

    - name: Install Android SDK and Accept Licenses
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME
        sdkmanager --version || true
        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;33.0.2" "platforms;android-33"

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
        
